name: Node.js Package

permissions:
  contents: read
  packages: write
on:
  push:
    branches:
      main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registery-url: https://npm.pkg.github.com/
          scope: '@Omid-Gharavi'
      - run: npm publish
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
