name: Publish Debug

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Print GitHub event (debug)
        run: |
          echo "EVENT_NAME=$GITHUB_EVENT_NAME"
          echo "REF=$GITHUB_REF"
          echo "SHA=$GITHUB_SHA"
          echo "Event JSON:"
          cat "$GITHUB_EVENT_PATH" || true

      - name: Setup Node and registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Check npm auth (safe)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # create local .npmrc to test auth
          printf "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}\n" > ~/.npmrc
          echo "npm registry:"
          npm config get registry
          echo "npm whoami (prints username if token OK; will fail if token invalid):"
          npm whoami --registry https://registry.npmjs.org/ || true

      - name: Dry-run publish (won't publish)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --dry-run --access public || true
