name: Publish Package to npmjs

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write   # required if you use --provenance

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js and npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}   # must be an npm automation token
        run: |
          # optional: sanity check
          npm --version
          node --version

          # dry-run to check what will be published (optional)
          npm publish --dry-run

          # real publish: include --access public for scoped packages
          npm publish --provenance --access public
