name: Publish Node package to GitHub Packages

# Prefer publishing on tags. If you want to publish on main commits, add branches: [ main ] here.
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          # configure the scope to the repository owner so setup-node writes the correct auth entry
          scope: "@${{ github.repository_owner }}"
      - run: npm ci
      - name: Build (optional)
        run: npm run build || echo "no build script"
      - name: Create .npmrc (fallback)
        run: |
          # Use the GITHUB_TOKEN to authenticate to the GitHub npm registry.
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          # Set the registry for the owner/org scope so scoped publishes go to GitHub Packages
          echo "@${GITHUB_REPOSITORY_OWNER}:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # If you use a scoped package (recommended) and want it public, --access public is valid.
          # If your package name is not scoped, omit --access public. Make sure package.json "name" is "@OWNER/name".
          npm publish --registry https://npm.pkg.github.com/ --access public || npm publish --registry https://npm.pkg.github.com/
